-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity naive_findClustersHLS2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    grid_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grid_ce0 : OUT STD_LOGIC;
    grid_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    pointsGrid_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pointsGrid_ce0 : OUT STD_LOGIC;
    pointsGrid_we0 : OUT STD_LOGIC;
    pointsGrid_d0 : OUT STD_LOGIC_VECTOR (95 downto 0) );
end;


architecture behav of naive_findClustersHLS2 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "naive_findClustersHLS2_naive_findClustersHLS2,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.002000,HLS_SYN_LAT=1656,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=368,HLS_SYN_LUT=1746,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal clusterGrid1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal clusterGrid1_ce0 : STD_LOGIC;
    signal clusterGrid1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal clusterGrid1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal clusterGrid1_ce1 : STD_LOGIC;
    signal clusterGrid1_we1 : STD_LOGIC;
    signal clusterGrid1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal clusterGrid1_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal clusterGrid2_ce0 : STD_LOGIC;
    signal clusterGrid2_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal clusterGrid2_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal clusterGrid2_ce1 : STD_LOGIC;
    signal clusterGrid2_we1 : STD_LOGIC;
    signal clusterGrid2_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_idle : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_ready : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_ce0 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce0 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce1 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_we1 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_done : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_idle : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_ready : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_ce0 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce0 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce1 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_ce1 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_we1 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_idle : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_ready : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_ce0 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_ce0 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_we0 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_d0 : STD_LOGIC_VECTOR (95 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_ce0 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_ce0 : STD_LOGIC;
    signal grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component naive_findClustersHLS2_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        grid_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        grid_ce0 : OUT STD_LOGIC;
        grid_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        clusterGrid1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        clusterGrid1_ce0 : OUT STD_LOGIC;
        clusterGrid1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        clusterGrid1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        clusterGrid1_ce1 : OUT STD_LOGIC;
        clusterGrid1_we1 : OUT STD_LOGIC;
        clusterGrid1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        clusterGrid1_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component naive_findClustersHLS2_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        grid_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        grid_ce0 : OUT STD_LOGIC;
        grid_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        clusterGrid1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        clusterGrid1_ce0 : OUT STD_LOGIC;
        clusterGrid1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        clusterGrid1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        clusterGrid1_ce1 : OUT STD_LOGIC;
        clusterGrid1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        clusterGrid2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        clusterGrid2_ce1 : OUT STD_LOGIC;
        clusterGrid2_we1 : OUT STD_LOGIC;
        clusterGrid2_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component naive_findClustersHLS2_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        grid_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        grid_ce0 : OUT STD_LOGIC;
        grid_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        pointsGrid_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        pointsGrid_ce0 : OUT STD_LOGIC;
        pointsGrid_we0 : OUT STD_LOGIC;
        pointsGrid_d0 : OUT STD_LOGIC_VECTOR (95 downto 0);
        clusterGrid1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        clusterGrid1_ce0 : OUT STD_LOGIC;
        clusterGrid1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        clusterGrid2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        clusterGrid2_ce0 : OUT STD_LOGIC;
        clusterGrid2_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component naive_findClustersHLS2_clusterGrid1_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (15 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component naive_findClustersHLS2_clusterGrid2_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    clusterGrid1_U : component naive_findClustersHLS2_clusterGrid1_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 144,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => clusterGrid1_address0,
        ce0 => clusterGrid1_ce0,
        q0 => clusterGrid1_q0,
        address1 => clusterGrid1_address1,
        ce1 => clusterGrid1_ce1,
        we1 => clusterGrid1_we1,
        d1 => clusterGrid1_d1,
        q1 => clusterGrid1_q1);

    clusterGrid2_U : component naive_findClustersHLS2_clusterGrid2_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 144,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_address0,
        ce0 => clusterGrid2_ce0,
        q0 => clusterGrid2_q0,
        address1 => clusterGrid2_address1,
        ce1 => clusterGrid2_ce1,
        we1 => clusterGrid2_we1,
        d1 => clusterGrid2_d1);

    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85 : component naive_findClustersHLS2_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start,
        ap_done => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done,
        ap_idle => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_idle,
        ap_ready => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_ready,
        grid_address0 => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_address0,
        grid_ce0 => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_ce0,
        grid_q0 => grid_q0,
        clusterGrid1_address0 => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address0,
        clusterGrid1_ce0 => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce0,
        clusterGrid1_q0 => clusterGrid1_q0,
        clusterGrid1_address1 => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address1,
        clusterGrid1_ce1 => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce1,
        clusterGrid1_we1 => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_we1,
        clusterGrid1_d1 => grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_d1,
        clusterGrid1_q1 => clusterGrid1_q1);

    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92 : component naive_findClustersHLS2_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start,
        ap_done => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_done,
        ap_idle => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_idle,
        ap_ready => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_ready,
        grid_address0 => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_address0,
        grid_ce0 => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_ce0,
        grid_q0 => grid_q0,
        clusterGrid1_address0 => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address0,
        clusterGrid1_ce0 => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce0,
        clusterGrid1_q0 => clusterGrid1_q0,
        clusterGrid1_address1 => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address1,
        clusterGrid1_ce1 => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce1,
        clusterGrid1_q1 => clusterGrid1_q1,
        clusterGrid2_address1 => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_address1,
        clusterGrid2_ce1 => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_ce1,
        clusterGrid2_we1 => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_we1,
        clusterGrid2_d1 => grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_d1);

    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100 : component naive_findClustersHLS2_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start,
        ap_done => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done,
        ap_idle => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_idle,
        ap_ready => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_ready,
        grid_address0 => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_address0,
        grid_ce0 => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_ce0,
        grid_q0 => grid_q0,
        pointsGrid_address0 => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_address0,
        pointsGrid_ce0 => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_ce0,
        pointsGrid_we0 => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_we0,
        pointsGrid_d0 => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_d0,
        clusterGrid1_address0 => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_address0,
        clusterGrid1_ce0 => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_ce0,
        clusterGrid1_q0 => clusterGrid1_q0,
        clusterGrid2_address0 => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_address0,
        clusterGrid2_ce0 => grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_ce0,
        clusterGrid2_q0 => clusterGrid2_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_ready = ap_const_logic_1)) then 
                    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_ready = ap_const_logic_1)) then 
                    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_ready = ap_const_logic_1)) then 
                    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done, grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_done, grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done)
    begin
        if ((grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_done)
    begin
        if ((grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done)
    begin
        if ((grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    clusterGrid1_address0_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address0, grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address0, grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_address0, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            clusterGrid1_address0 <= grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            clusterGrid1_address0 <= grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            clusterGrid1_address0 <= grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address0;
        else 
            clusterGrid1_address0 <= "XXXXXXXX";
        end if; 
    end process;


    clusterGrid1_address1_assign_proc : process(ap_CS_fsm_state1, grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address1, grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            clusterGrid1_address1 <= ap_const_lv64_0(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            clusterGrid1_address1 <= grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            clusterGrid1_address1 <= grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address1;
        else 
            clusterGrid1_address1 <= "XXXXXXXX";
        end if; 
    end process;


    clusterGrid1_ce0_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce0, grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce0, grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            clusterGrid1_ce0 <= grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            clusterGrid1_ce0 <= grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            clusterGrid1_ce0 <= grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce0;
        else 
            clusterGrid1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    clusterGrid1_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce1, grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            clusterGrid1_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            clusterGrid1_ce1 <= grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            clusterGrid1_ce1 <= grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce1;
        else 
            clusterGrid1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    clusterGrid1_d1_assign_proc : process(ap_CS_fsm_state1, grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_d1, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            clusterGrid1_d1 <= ap_const_lv16_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            clusterGrid1_d1 <= grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_d1;
        else 
            clusterGrid1_d1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    clusterGrid1_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_we1, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            clusterGrid1_we1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            clusterGrid1_we1 <= grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_we1;
        else 
            clusterGrid1_we1 <= ap_const_logic_0;
        end if; 
    end process;


    clusterGrid2_address1_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_address1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            clusterGrid2_address1 <= ap_const_lv64_0(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            clusterGrid2_address1 <= grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_address1;
        else 
            clusterGrid2_address1 <= "XXXXXXXX";
        end if; 
    end process;


    clusterGrid2_ce0_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_ce0, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            clusterGrid2_ce0 <= grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_ce0;
        else 
            clusterGrid2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    clusterGrid2_ce1_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done, grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_ce1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            clusterGrid2_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            clusterGrid2_ce1 <= grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_ce1;
        else 
            clusterGrid2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    clusterGrid2_d1_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_d1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            clusterGrid2_d1 <= ap_const_lv16_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            clusterGrid2_d1 <= grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_d1;
        else 
            clusterGrid2_d1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    clusterGrid2_we1_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done, grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_we1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            clusterGrid2_we1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            clusterGrid2_we1 <= grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_we1;
        else 
            clusterGrid2_we1 <= ap_const_logic_0;
        end if; 
    end process;


    grid_address0_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_address0, grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_address0, grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_address0, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grid_address0 <= grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grid_address0 <= grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grid_address0 <= grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_address0;
        else 
            grid_address0 <= "XXXXXXXX";
        end if; 
    end process;


    grid_ce0_assign_proc : process(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_ce0, grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_ce0, grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grid_ce0 <= grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grid_ce0 <= grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grid_ce0 <= grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_ce0;
        else 
            grid_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start <= grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg;
    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start <= grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg;
    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start <= grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg;
    pointsGrid_address0 <= grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_address0;
    pointsGrid_ce0 <= grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_ce0;
    pointsGrid_d0 <= grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_d0;
    pointsGrid_we0 <= grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_we0;
end behav;
