// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module naive_findClustersHLS1_naive_findClustersHLS1_Pipeline_VITIS_LOOP_199_5_VITIS_LOOP_200_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        clusterArray_x_address0,
        clusterArray_x_ce0,
        clusterArray_x_we0,
        clusterArray_x_d0,
        clusterArray_y_address0,
        clusterArray_y_ce0,
        clusterArray_y_we0,
        clusterArray_y_d0,
        clusterArray_clusterID_address0,
        clusterArray_clusterID_ce0,
        clusterArray_clusterID_we0,
        clusterArray_clusterID_d0,
        clusterGrid_x_address0,
        clusterGrid_x_ce0,
        clusterGrid_x_q0,
        clusterGrid_y_address0,
        clusterGrid_y_ce0,
        clusterGrid_y_q0,
        clusterGrid_clusterID_address0,
        clusterGrid_clusterID_ce0,
        clusterGrid_clusterID_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] clusterArray_x_address0;
output   clusterArray_x_ce0;
output   clusterArray_x_we0;
output  [31:0] clusterArray_x_d0;
output  [6:0] clusterArray_y_address0;
output   clusterArray_y_ce0;
output   clusterArray_y_we0;
output  [31:0] clusterArray_y_d0;
output  [6:0] clusterArray_clusterID_address0;
output   clusterArray_clusterID_ce0;
output   clusterArray_clusterID_we0;
output  [31:0] clusterArray_clusterID_d0;
output  [6:0] clusterGrid_x_address0;
output   clusterGrid_x_ce0;
input  [31:0] clusterGrid_x_q0;
output  [6:0] clusterGrid_y_address0;
output   clusterGrid_y_ce0;
input  [31:0] clusterGrid_y_q0;
output  [6:0] clusterGrid_clusterID_address0;
output   clusterGrid_clusterID_ce0;
input  [31:0] clusterGrid_clusterID_q0;

reg ap_idle;
reg clusterArray_x_ce0;
reg clusterArray_x_we0;
reg clusterArray_y_ce0;
reg clusterArray_y_we0;
reg clusterArray_clusterID_ce0;
reg clusterArray_clusterID_we0;
reg clusterGrid_x_ce0;
reg clusterGrid_y_ce0;
reg clusterGrid_clusterID_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln199_fu_165_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln201_2_fu_247_p1;
reg   [63:0] zext_ln201_2_reg_299;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0;
reg   [3:0] j_fu_54;
wire   [3:0] add_ln200_fu_254_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_load;
reg   [3:0] i_fu_58;
wire   [3:0] select_ln199_1_fu_203_p3;
reg   [3:0] ap_sig_allocacmp_i_load;
reg   [6:0] indvar_flatten6_fu_62;
wire   [6:0] add_ln199_1_fu_171_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten6_load;
wire   [0:0] icmp_ln200_fu_189_p2;
wire   [3:0] add_ln199_fu_183_p2;
wire   [4:0] tmp_7_fu_219_p3;
wire   [6:0] tmp_6_fu_211_p3;
wire   [6:0] zext_ln201_fu_227_p1;
wire   [3:0] select_ln199_fu_195_p3;
wire   [6:0] add_ln201_fu_231_p2;
wire   [6:0] zext_ln201_1_fu_237_p1;
wire   [6:0] add_ln201_1_fu_241_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

naive_findClustersHLS1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln199_fu_165_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_58 <= select_ln199_1_fu_203_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_58 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln199_fu_165_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_62 <= add_ln199_1_fu_171_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_62 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln199_fu_165_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_54 <= add_ln200_fu_254_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_54 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln199_fu_165_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln201_2_reg_299[6 : 0] <= zext_ln201_2_fu_247_p1[6 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln199_fu_165_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        clusterArray_clusterID_ce0 = 1'b1;
    end else begin
        clusterArray_clusterID_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        clusterArray_clusterID_we0 = 1'b1;
    end else begin
        clusterArray_clusterID_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        clusterArray_x_ce0 = 1'b1;
    end else begin
        clusterArray_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        clusterArray_x_we0 = 1'b1;
    end else begin
        clusterArray_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        clusterArray_y_ce0 = 1'b1;
    end else begin
        clusterArray_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        clusterArray_y_we0 = 1'b1;
    end else begin
        clusterArray_y_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        clusterGrid_clusterID_ce0 = 1'b1;
    end else begin
        clusterGrid_clusterID_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        clusterGrid_x_ce0 = 1'b1;
    end else begin
        clusterGrid_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        clusterGrid_y_ce0 = 1'b1;
    end else begin
        clusterGrid_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln199_1_fu_171_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 7'd1);

assign add_ln199_fu_183_p2 = (ap_sig_allocacmp_i_load + 4'd1);

assign add_ln200_fu_254_p2 = (select_ln199_fu_195_p3 + 4'd1);

assign add_ln201_1_fu_241_p2 = (add_ln201_fu_231_p2 + zext_ln201_1_fu_237_p1);

assign add_ln201_fu_231_p2 = (tmp_6_fu_211_p3 + zext_ln201_fu_227_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign clusterArray_clusterID_address0 = zext_ln201_2_reg_299;

assign clusterArray_clusterID_d0 = clusterGrid_clusterID_q0;

assign clusterArray_x_address0 = zext_ln201_2_reg_299;

assign clusterArray_x_d0 = clusterGrid_x_q0;

assign clusterArray_y_address0 = zext_ln201_2_reg_299;

assign clusterArray_y_d0 = clusterGrid_y_q0;

assign clusterGrid_clusterID_address0 = zext_ln201_2_fu_247_p1;

assign clusterGrid_x_address0 = zext_ln201_2_fu_247_p1;

assign clusterGrid_y_address0 = zext_ln201_2_fu_247_p1;

assign icmp_ln199_fu_165_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln200_fu_189_p2 = ((ap_sig_allocacmp_j_load == 4'd10) ? 1'b1 : 1'b0);

assign select_ln199_1_fu_203_p3 = ((icmp_ln200_fu_189_p2[0:0] == 1'b1) ? add_ln199_fu_183_p2 : ap_sig_allocacmp_i_load);

assign select_ln199_fu_195_p3 = ((icmp_ln200_fu_189_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j_load);

assign tmp_6_fu_211_p3 = {{select_ln199_1_fu_203_p3}, {3'd0}};

assign tmp_7_fu_219_p3 = {{select_ln199_1_fu_203_p3}, {1'd0}};

assign zext_ln201_1_fu_237_p1 = select_ln199_fu_195_p3;

assign zext_ln201_2_fu_247_p1 = add_ln201_1_fu_241_p2;

assign zext_ln201_fu_227_p1 = tmp_7_fu_219_p3;

always @ (posedge ap_clk) begin
    zext_ln201_2_reg_299[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //naive_findClustersHLS1_naive_findClustersHLS1_Pipeline_VITIS_LOOP_199_5_VITIS_LOOP_200_6
