-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity naive_findClustersHLS2_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    grid_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grid_ce0 : OUT STD_LOGIC;
    grid_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    pointsGrid_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pointsGrid_ce0 : OUT STD_LOGIC;
    pointsGrid_we0 : OUT STD_LOGIC;
    pointsGrid_d0 : OUT STD_LOGIC_VECTOR (95 downto 0);
    clusterGrid1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    clusterGrid1_ce0 : OUT STD_LOGIC;
    clusterGrid1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    clusterGrid2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    clusterGrid2_ce0 : OUT STD_LOGIC;
    clusterGrid2_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of naive_findClustersHLS2_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_90 : STD_LOGIC_VECTOR (7 downto 0) := "10010000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln280_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln280_fu_178_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln280_reg_336 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln280_1_fu_186_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln280_1_reg_342 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln284_2_fu_230_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln284_2_reg_347 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_fu_66 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln282_fu_237_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (3 downto 0);
    signal i_fu_70 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten13_fu_74 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln280_1_fu_154_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten13_load : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln282_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln280_fu_166_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_202_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_194_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln284_fu_210_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln284_fu_214_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln284_1_fu_220_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln284_fu_224_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln280_fu_258_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_264_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal icmp_ln285_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal clusterID_fu_281_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln288_fu_261_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_289_p4 : STD_LOGIC_VECTOR (79 downto 0);
    signal zext_ln285_fu_271_p1 : STD_LOGIC_VECTOR (79 downto 0);
    signal select_ln284_fu_299_p3 : STD_LOGIC_VECTOR (79 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component naive_findClustersHLS2_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component naive_findClustersHLS2_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln280_fu_148_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_70 <= select_ln280_1_fu_186_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_70 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten13_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln280_fu_148_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten13_fu_74 <= add_ln280_1_fu_154_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten13_fu_74 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln280_fu_148_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_66 <= add_ln282_fu_237_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_66 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln280_fu_148_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln280_1_reg_342 <= select_ln280_1_fu_186_p3;
                select_ln280_reg_336 <= select_ln280_fu_178_p3;
                    zext_ln284_2_reg_347(7 downto 0) <= zext_ln284_2_fu_230_p1(7 downto 0);
            end if;
        end if;
    end process;
    zext_ln284_2_reg_347(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln280_1_fu_154_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten13_load) + unsigned(ap_const_lv8_1));
    add_ln280_fu_166_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv4_1));
    add_ln282_fu_237_p2 <= std_logic_vector(unsigned(select_ln280_fu_178_p3) + unsigned(ap_const_lv4_1));
    add_ln284_fu_224_p2 <= std_logic_vector(unsigned(sub_ln284_fu_214_p2) + unsigned(zext_ln284_1_fu_220_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln280_fu_148_p2)
    begin
        if (((icmp_ln280_fu_148_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_70)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_70;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten13_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten13_fu_74)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten13_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten13_load <= indvar_flatten13_fu_74;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_66, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_66;
        end if; 
    end process;

    clusterGrid1_address0 <= zext_ln284_2_fu_230_p1(8 - 1 downto 0);

    clusterGrid1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            clusterGrid1_ce0 <= ap_const_logic_1;
        else 
            clusterGrid1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    clusterGrid2_address0 <= zext_ln284_2_fu_230_p1(8 - 1 downto 0);

    clusterGrid2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            clusterGrid2_ce0 <= ap_const_logic_1;
        else 
            clusterGrid2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    clusterID_fu_281_p3 <= 
        clusterGrid1_q0 when (icmp_ln285_fu_275_p2(0) = '1') else 
        clusterGrid2_q0;
    grid_address0 <= zext_ln284_2_fu_230_p1(8 - 1 downto 0);

    grid_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grid_ce0 <= ap_const_logic_1;
        else 
            grid_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln280_fu_148_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten13_load = ap_const_lv8_90) else "0";
    icmp_ln282_fu_172_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv4_C) else "0";
    icmp_ln285_fu_275_p2 <= "1" when (clusterGrid2_q0 = ap_const_lv16_0) else "0";
    pointsGrid_address0 <= zext_ln284_2_reg_347(8 - 1 downto 0);

    pointsGrid_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pointsGrid_ce0 <= ap_const_logic_1;
        else 
            pointsGrid_ce0 <= ap_const_logic_0;
        end if; 
    end process;

        pointsGrid_d0 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln284_fu_299_p3),96));


    pointsGrid_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pointsGrid_we0 <= ap_const_logic_1;
        else 
            pointsGrid_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln280_1_fu_186_p3 <= 
        add_ln280_fu_166_p2 when (icmp_ln282_fu_172_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln280_fu_178_p3 <= 
        ap_const_lv4_0 when (icmp_ln282_fu_172_p2(0) = '1') else 
        ap_sig_allocacmp_j_load;
    select_ln284_fu_299_p3 <= 
        tmp_1_fu_289_p4 when (grid_q0(0) = '1') else 
        zext_ln285_fu_271_p1;
    sub_ln284_fu_214_p2 <= std_logic_vector(unsigned(tmp_s_fu_194_p3) - unsigned(zext_ln284_fu_210_p1));
    tmp_1_fu_289_p4 <= ((clusterID_fu_281_p3 & zext_ln288_fu_261_p1) & zext_ln280_fu_258_p1);
    tmp_2_fu_202_p3 <= (select_ln280_1_fu_186_p3 & ap_const_lv2_0);
    tmp_fu_264_p3 <= (select_ln280_reg_336 & zext_ln280_fu_258_p1);
    tmp_s_fu_194_p3 <= (select_ln280_1_fu_186_p3 & ap_const_lv4_0);
    zext_ln280_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln280_1_reg_342),32));
    zext_ln284_1_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln280_fu_178_p3),8));
    zext_ln284_2_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln284_fu_224_p2),64));
    zext_ln284_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_202_p3),8));
    zext_ln285_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_264_p3),80));
    zext_ln288_fu_261_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln280_reg_336),32));
end behav;
