// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module naive_findClustersHLS1_naive_findClustersHLS1_Pipeline_VITIS_LOOP_168_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stackIndex_3,
        stack_x_address0,
        stack_x_ce0,
        stack_x_we0,
        stack_x_d0,
        stack_x_q0,
        stack_y_address0,
        stack_y_ce0,
        stack_y_we0,
        stack_y_d0,
        stack_y_q0,
        grid_address0,
        grid_ce0,
        grid_q0,
        grid_address1,
        grid_ce1,
        grid_q1,
        clusterGrid_x_address0,
        clusterGrid_x_ce0,
        clusterGrid_x_we0,
        clusterGrid_x_d0,
        clusterGrid_x_address1,
        clusterGrid_x_ce1,
        clusterGrid_x_we1,
        clusterGrid_x_d1,
        clusterGrid_y_address0,
        clusterGrid_y_ce0,
        clusterGrid_y_we0,
        clusterGrid_y_d0,
        clusterGrid_y_address1,
        clusterGrid_y_ce1,
        clusterGrid_y_we1,
        clusterGrid_y_d1,
        clusterGrid_clusterID_address0,
        clusterGrid_clusterID_ce0,
        clusterGrid_clusterID_we0,
        clusterGrid_clusterID_d0,
        clusterGrid_clusterID_q0,
        clusterGrid_clusterID_address1,
        clusterGrid_clusterID_ce1,
        clusterGrid_clusterID_we1,
        clusterGrid_clusterID_d1,
        clusterGrid_clusterID_q1,
        clusterID_3,
        stackIndex_2_out,
        stackIndex_2_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] stackIndex_3;
output  [6:0] stack_x_address0;
output   stack_x_ce0;
output   stack_x_we0;
output  [31:0] stack_x_d0;
input  [31:0] stack_x_q0;
output  [6:0] stack_y_address0;
output   stack_y_ce0;
output   stack_y_we0;
output  [31:0] stack_y_d0;
input  [31:0] stack_y_q0;
output  [6:0] grid_address0;
output   grid_ce0;
input  [31:0] grid_q0;
output  [6:0] grid_address1;
output   grid_ce1;
input  [31:0] grid_q1;
output  [6:0] clusterGrid_x_address0;
output   clusterGrid_x_ce0;
output   clusterGrid_x_we0;
output  [31:0] clusterGrid_x_d0;
output  [6:0] clusterGrid_x_address1;
output   clusterGrid_x_ce1;
output   clusterGrid_x_we1;
output  [31:0] clusterGrid_x_d1;
output  [6:0] clusterGrid_y_address0;
output   clusterGrid_y_ce0;
output   clusterGrid_y_we0;
output  [31:0] clusterGrid_y_d0;
output  [6:0] clusterGrid_y_address1;
output   clusterGrid_y_ce1;
output   clusterGrid_y_we1;
output  [31:0] clusterGrid_y_d1;
output  [6:0] clusterGrid_clusterID_address0;
output   clusterGrid_clusterID_ce0;
output   clusterGrid_clusterID_we0;
output  [31:0] clusterGrid_clusterID_d0;
input  [31:0] clusterGrid_clusterID_q0;
output  [6:0] clusterGrid_clusterID_address1;
output   clusterGrid_clusterID_ce1;
output   clusterGrid_clusterID_we1;
output  [31:0] clusterGrid_clusterID_d1;
input  [31:0] clusterGrid_clusterID_q1;
input  [31:0] clusterID_3;
output  [31:0] stackIndex_2_out;
output   stackIndex_2_out_ap_vld;

reg ap_idle;
reg[6:0] stack_x_address0;
reg stack_x_ce0;
reg stack_x_we0;
reg[31:0] stack_x_d0;
reg[6:0] stack_y_address0;
reg stack_y_ce0;
reg stack_y_we0;
reg[31:0] stack_y_d0;
reg[6:0] grid_address0;
reg grid_ce0;
reg[6:0] grid_address1;
reg grid_ce1;
reg[6:0] clusterGrid_x_address0;
reg clusterGrid_x_ce0;
reg clusterGrid_x_we0;
reg[31:0] clusterGrid_x_d0;
reg[6:0] clusterGrid_x_address1;
reg clusterGrid_x_ce1;
reg clusterGrid_x_we1;
reg[31:0] clusterGrid_x_d1;
reg[6:0] clusterGrid_y_address0;
reg clusterGrid_y_ce0;
reg clusterGrid_y_we0;
reg[31:0] clusterGrid_y_d0;
reg[6:0] clusterGrid_y_address1;
reg clusterGrid_y_ce1;
reg clusterGrid_y_we1;
reg[31:0] clusterGrid_y_d1;
reg[6:0] clusterGrid_clusterID_address0;
reg clusterGrid_clusterID_ce0;
reg clusterGrid_clusterID_we0;
reg[6:0] clusterGrid_clusterID_address1;
reg clusterGrid_clusterID_ce1;
reg clusterGrid_clusterID_we1;
reg stackIndex_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln168_fu_637_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state11;
wire    ap_block_state11_pp0_stage10_iter0;
reg   [31:0] stackIndex_5_0_reg_474;
reg   [31:0] stackIndex_5_1_reg_488;
reg   [31:0] stackIndex_5_2_reg_505;
reg   [31:0] stackIndex_5_3_reg_522;
reg   [31:0] stackIndex_1_reg_1226;
reg   [0:0] icmp_ln168_reg_1231;
wire   [31:0] stackIndex_2_fu_643_p2;
reg   [31:0] stackIndex_2_reg_1235;
reg   [6:0] stack_x_addr_reg_1242;
reg   [6:0] stack_y_addr_reg_1247;
reg   [31:0] hit_x_reg_1252;
wire    ap_CS_fsm_state2;
wire    ap_block_state2_pp0_stage1_iter0;
wire   [5:0] trunc_ln170_fu_655_p1;
reg   [5:0] trunc_ln170_reg_1260;
wire   [3:0] trunc_ln170_1_fu_659_p1;
reg   [3:0] trunc_ln170_1_reg_1265;
reg   [31:0] hit_y_reg_1270;
wire   [31:0] add_ln175_fu_663_p2;
reg   [31:0] add_ln175_reg_1281;
wire   [5:0] trunc_ln176_fu_669_p1;
reg   [5:0] trunc_ln176_reg_1288;
wire   [3:0] trunc_ln176_1_fu_673_p1;
reg   [3:0] trunc_ln176_1_reg_1294;
wire   [31:0] add_ln176_fu_677_p2;
reg   [31:0] add_ln176_reg_1300;
wire   [0:0] icmp_ln180_fu_683_p2;
reg   [0:0] icmp_ln180_reg_1308;
wire   [0:0] icmp_ln180_1_fu_689_p2;
reg   [0:0] icmp_ln180_1_reg_1314;
wire   [0:0] and_ln180_fu_695_p2;
reg   [0:0] and_ln180_reg_1319;
reg   [6:0] clusterGrid_x_addr_reg_1328;
reg   [6:0] clusterGrid_y_addr_reg_1333;
reg   [6:0] clusterGrid_clusterID_addr_reg_1338;
wire   [0:0] icmp_ln180_3_fu_745_p2;
reg   [0:0] icmp_ln180_3_reg_1343;
wire   [0:0] and_ln180_1_fu_751_p2;
reg   [0:0] and_ln180_1_reg_1348;
reg   [6:0] clusterGrid_x_addr_1_reg_1357;
reg   [6:0] clusterGrid_y_addr_1_reg_1362;
reg   [6:0] clusterGrid_clusterID_addr_1_reg_1367;
wire   [0:0] grp_fu_605_p2;
reg   [0:0] icmp_ln184_reg_1372;
wire    ap_CS_fsm_state3;
wire    ap_block_state3_pp0_stage2_iter0;
wire   [0:0] grp_fu_611_p2;
reg   [0:0] icmp_ln184_8_reg_1376;
wire   [31:0] add_ln175_1_fu_801_p2;
reg   [31:0] add_ln175_1_reg_1380;
wire   [5:0] trunc_ln180_fu_806_p1;
reg   [5:0] trunc_ln180_reg_1387;
wire   [3:0] trunc_ln180_1_fu_810_p1;
reg   [3:0] trunc_ln180_1_reg_1393;
wire   [0:0] icmp_ln180_2_fu_814_p2;
reg   [0:0] icmp_ln180_2_reg_1399;
wire   [0:0] and_ln180_2_fu_820_p2;
reg   [0:0] and_ln180_2_reg_1405;
reg   [6:0] clusterGrid_x_addr_2_reg_1414;
reg   [6:0] clusterGrid_y_addr_2_reg_1419;
reg   [6:0] clusterGrid_clusterID_addr_2_reg_1424;
wire   [0:0] icmp_ln180_4_fu_868_p2;
reg   [0:0] icmp_ln180_4_reg_1429;
wire   [0:0] and_ln180_3_fu_873_p2;
reg   [0:0] and_ln180_3_reg_1434;
reg   [6:0] clusterGrid_x_addr_3_reg_1443;
reg   [6:0] clusterGrid_y_addr_3_reg_1448;
reg   [6:0] clusterGrid_clusterID_addr_3_reg_1453;
wire   [0:0] grp_fu_617_p2;
reg   [0:0] icmp_ln184_1_reg_1458;
wire    ap_CS_fsm_state4;
wire    ap_block_state4_pp0_stage3_iter0;
wire   [0:0] grp_fu_623_p2;
reg   [0:0] icmp_ln184_9_reg_1462;
reg   [0:0] icmp_ln184_2_reg_1466;
reg   [0:0] icmp_ln184_3_reg_1470;
wire   [0:0] and_ln180_4_fu_926_p2;
reg   [0:0] and_ln180_4_reg_1474;
reg   [6:0] clusterGrid_x_addr_4_reg_1483;
reg   [6:0] clusterGrid_y_addr_4_reg_1488;
reg   [6:0] clusterGrid_clusterID_addr_4_reg_1493;
wire   [31:0] add_ln176_1_fu_971_p2;
reg   [31:0] add_ln176_1_reg_1498;
wire   [0:0] and_ln180_5_fu_982_p2;
reg   [0:0] and_ln180_5_reg_1505;
reg   [6:0] clusterGrid_x_addr_5_reg_1514;
reg   [6:0] clusterGrid_y_addr_5_reg_1519;
reg   [6:0] clusterGrid_clusterID_addr_5_reg_1524;
wire   [0:0] and_ln180_6_fu_1029_p2;
reg   [0:0] and_ln180_6_reg_1529;
wire   [6:0] add_ln184_13_fu_1062_p2;
reg   [6:0] add_ln184_13_reg_1533;
wire   [0:0] and_ln180_7_fu_1068_p2;
reg   [0:0] and_ln180_7_reg_1538;
wire   [6:0] add_ln184_15_fu_1101_p2;
reg   [6:0] add_ln184_15_reg_1542;
reg   [0:0] icmp_ln184_10_reg_1547;
wire    ap_CS_fsm_state5;
wire    ap_block_state5_pp0_stage4_iter0;
reg   [0:0] icmp_ln184_11_reg_1551;
reg   [0:0] icmp_ln184_4_reg_1555;
reg   [0:0] icmp_ln184_5_reg_1559;
reg   [6:0] clusterGrid_x_addr_6_reg_1568;
reg   [6:0] clusterGrid_y_addr_6_reg_1573;
reg   [6:0] clusterGrid_clusterID_addr_6_reg_1578;
reg   [6:0] clusterGrid_x_addr_7_reg_1588;
reg   [6:0] clusterGrid_y_addr_7_reg_1593;
reg   [6:0] clusterGrid_clusterID_addr_7_reg_1598;
reg   [0:0] icmp_ln184_12_reg_1603;
wire    ap_CS_fsm_state6;
wire    ap_block_state6_pp0_stage5_iter0;
reg   [0:0] icmp_ln184_13_reg_1607;
reg   [0:0] icmp_ln184_6_reg_1611;
reg   [0:0] icmp_ln184_7_reg_1615;
wire   [31:0] add_ln186_2_fu_1140_p2;
reg   [31:0] add_ln186_2_reg_1619;
wire    ap_CS_fsm_state7;
wire    ap_block_state7_pp0_stage6_iter0;
reg   [0:0] icmp_ln184_14_reg_1624;
reg   [0:0] icmp_ln184_15_reg_1628;
wire   [31:0] add_ln186_4_fu_1165_p2;
wire    ap_CS_fsm_state9;
wire    ap_block_state9_pp0_stage8_iter0;
wire   [31:0] add_ln186_5_fu_1177_p2;
wire    ap_CS_fsm_state10;
wire    ap_block_state10_pp0_stage9_iter0;
reg   [31:0] ap_phi_mux_stackIndex_5_0_phi_fu_477_p8;
reg   [31:0] ap_phi_reg_pp0_iter0_stackIndex_5_0_reg_474;
reg   [31:0] ap_phi_mux_stackIndex_5_1_phi_fu_491_p8;
wire   [31:0] add_ln186_fu_919_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_stackIndex_5_1_reg_488;
reg   [31:0] ap_phi_mux_stackIndex_5_2_phi_fu_508_p8;
wire   [31:0] add_ln186_1_fu_1113_p2;
reg   [31:0] ap_phi_reg_pp0_iter0_stackIndex_5_2_reg_505;
reg   [31:0] ap_phi_mux_stackIndex_5_3_phi_fu_525_p8;
reg   [31:0] ap_phi_reg_pp0_iter0_stackIndex_5_3_reg_522;
wire    ap_CS_fsm_state8;
wire    ap_block_state8_pp0_stage7_iter0;
reg   [31:0] ap_phi_mux_stackIndex_5_4_phi_fu_542_p8;
wire   [31:0] add_ln186_3_fu_1158_p2;
reg   [31:0] ap_phi_reg_pp0_iter0_stackIndex_5_4_reg_539;
reg   [31:0] ap_phi_reg_pp0_iter0_stackIndex_5_5_reg_556;
reg   [31:0] ap_phi_reg_pp0_iter0_stackIndex_5_6_reg_573;
reg   [31:0] ap_phi_mux_stackIndex_5_7_phi_fu_592_p8;
wire   [31:0] add_ln186_6_fu_1189_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_stackIndex_5_7_reg_589;
wire   [63:0] zext_ln170_fu_649_p1;
wire   [63:0] zext_ln184_1_fu_737_p1;
wire   [63:0] zext_ln184_3_fu_793_p1;
wire   [63:0] zext_ln184_5_fu_860_p1;
wire   [63:0] zext_ln184_7_fu_911_p1;
wire   [63:0] zext_ln184_9_fu_963_p1;
wire   [63:0] zext_ln184_11_fu_1021_p1;
wire   [63:0] zext_ln186_fu_1107_p1;
wire   [63:0] zext_ln184_13_fu_1120_p1;
wire   [63:0] zext_ln184_15_fu_1127_p1;
wire   [63:0] zext_ln186_1_fu_1134_p1;
wire   [63:0] zext_ln186_2_fu_1146_p1;
wire   [63:0] zext_ln186_3_fu_1152_p1;
wire   [63:0] zext_ln186_4_fu_1171_p1;
wire   [63:0] zext_ln186_5_fu_1183_p1;
wire   [63:0] zext_ln186_6_fu_1196_p1;
reg   [31:0] stackIndex_fu_52;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_stackIndex_1;
wire   [6:0] tmp_8_fu_701_p3;
wire   [6:0] tmp_9_fu_709_p3;
wire   [3:0] trunc_ln184_fu_723_p1;
wire   [6:0] add_ln184_fu_717_p2;
wire   [6:0] zext_ln184_fu_727_p1;
wire   [6:0] add_ln184_1_fu_731_p2;
wire   [6:0] tmp_s_fu_757_p3;
wire   [6:0] tmp_1_fu_765_p3;
wire   [3:0] trunc_ln184_1_fu_779_p1;
wire   [6:0] add_ln184_2_fu_773_p2;
wire   [6:0] zext_ln184_2_fu_783_p1;
wire   [6:0] add_ln184_3_fu_787_p2;
wire   [6:0] tmp_2_fu_825_p3;
wire   [6:0] tmp_3_fu_833_p3;
wire   [3:0] trunc_ln184_2_fu_847_p1;
wire   [6:0] add_ln184_4_fu_841_p2;
wire   [6:0] zext_ln184_4_fu_850_p1;
wire   [6:0] add_ln184_5_fu_854_p2;
wire   [6:0] tmp_4_fu_878_p3;
wire   [6:0] tmp_5_fu_885_p3;
wire   [3:0] trunc_ln184_3_fu_898_p1;
wire   [6:0] add_ln184_6_fu_892_p2;
wire   [6:0] zext_ln184_6_fu_901_p1;
wire   [6:0] add_ln184_7_fu_905_p2;
wire   [6:0] tmp_6_fu_930_p3;
wire   [6:0] tmp_7_fu_937_p3;
wire   [3:0] trunc_ln184_4_fu_950_p1;
wire   [6:0] add_ln184_8_fu_944_p2;
wire   [6:0] zext_ln184_8_fu_953_p1;
wire   [6:0] add_ln184_9_fu_957_p2;
wire   [0:0] icmp_ln180_5_fu_976_p2;
wire   [6:0] tmp_10_fu_987_p3;
wire   [6:0] tmp_11_fu_994_p3;
wire   [3:0] trunc_ln184_5_fu_1007_p1;
wire   [6:0] add_ln184_10_fu_1001_p2;
wire   [6:0] zext_ln184_10_fu_1011_p1;
wire   [6:0] add_ln184_11_fu_1015_p2;
wire   [6:0] tmp_12_fu_1034_p3;
wire   [6:0] tmp_13_fu_1041_p3;
wire   [3:0] trunc_ln184_6_fu_1054_p1;
wire   [6:0] add_ln184_12_fu_1048_p2;
wire   [6:0] zext_ln184_12_fu_1058_p1;
wire   [6:0] tmp_14_fu_1073_p3;
wire   [6:0] tmp_15_fu_1080_p3;
wire   [3:0] trunc_ln184_7_fu_1093_p1;
wire   [6:0] add_ln184_14_fu_1087_p2;
wire   [6:0] zext_ln184_14_fu_1097_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_start_int;
reg    ap_condition_254;
reg    ap_condition_320;
reg    ap_condition_1090;
reg    ap_condition_1094;
reg    ap_condition_1098;
reg    ap_condition_1102;
reg    ap_condition_1107;
reg    ap_condition_1111;
reg    ap_condition_1115;
reg    ap_condition_1119;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 ap_done_reg = 1'b0;
end

naive_findClustersHLS1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln184_13_reg_1607 == 1'd0) & (icmp_ln184_5_reg_1559 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_5_reg_1559 == 1'd1) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'd0 == and_ln180_5_reg_1505) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        ap_phi_reg_pp0_iter0_stackIndex_5_5_reg_556 <= ap_phi_mux_stackIndex_5_4_phi_fu_542_p8;
    end else if (((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1))) begin
        ap_phi_reg_pp0_iter0_stackIndex_5_5_reg_556 <= add_ln186_4_fu_1165_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln184_14_reg_1624 == 1'd0) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_6_reg_1611 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'd0 == and_ln180_6_reg_1529) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        ap_phi_reg_pp0_iter0_stackIndex_5_6_reg_573 <= ap_phi_reg_pp0_iter0_stackIndex_5_5_reg_556;
    end else if (((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1))) begin
        ap_phi_reg_pp0_iter0_stackIndex_5_6_reg_573 <= add_ln186_5_fu_1177_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_617_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stackIndex_5_0_reg_474 <= stackIndex_2_reg_1235;
    end else if (((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stackIndex_5_0_reg_474 <= stackIndex_1_reg_1226;
    end else if (((1'b1 == ap_CS_fsm_state4) | (~(icmp_ln168_reg_1231 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        stackIndex_5_0_reg_474 <= ap_phi_reg_pp0_iter0_stackIndex_5_0_reg_474;
    end
end

always @ (posedge ap_clk) begin
    if ((((grp_fu_623_p2 == 1'd0) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_8_reg_1376 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'd0 == and_ln180_1_reg_1348) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        stackIndex_5_1_reg_488 <= ap_phi_mux_stackIndex_5_0_phi_fu_477_p8;
    end else if (((grp_fu_623_p2 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stackIndex_5_1_reg_488 <= add_ln186_fu_919_p2;
    end else if ((~(icmp_ln168_reg_1231 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        stackIndex_5_1_reg_488 <= ap_phi_reg_pp0_iter0_stackIndex_5_1_reg_488;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln184_2_reg_1466 == 1'd0) & (grp_fu_617_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stackIndex_5_2_reg_505 <= stackIndex_5_1_reg_488;
    end else if (((icmp_ln184_2_reg_1466 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stackIndex_5_2_reg_505 <= add_ln186_1_fu_1113_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) | (~(icmp_ln168_reg_1231 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        stackIndex_5_2_reg_505 <= ap_phi_reg_pp0_iter0_stackIndex_5_2_reg_505;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stackIndex_5_3_reg_522 <= add_ln186_2_reg_1619;
    end else if (((1'b1 == ap_CS_fsm_state8) | (~(icmp_ln168_reg_1231 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        stackIndex_5_3_reg_522 <= ap_phi_reg_pp0_iter0_stackIndex_5_3_reg_522;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        stackIndex_fu_52 <= stackIndex_3;
    end else if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stackIndex_fu_52 <= ap_phi_mux_stackIndex_5_7_phi_fu_592_p8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln168_reg_1231 == 1'd1))) begin
        add_ln175_1_reg_1380 <= add_ln175_1_fu_801_p2;
        and_ln180_2_reg_1405 <= and_ln180_2_fu_820_p2;
        and_ln180_3_reg_1434 <= and_ln180_3_fu_873_p2;
        icmp_ln180_2_reg_1399 <= icmp_ln180_2_fu_814_p2;
        icmp_ln180_4_reg_1429 <= icmp_ln180_4_fu_868_p2;
        trunc_ln180_1_reg_1393 <= trunc_ln180_1_fu_810_p1;
        trunc_ln180_reg_1387 <= trunc_ln180_fu_806_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln175_reg_1281 <= add_ln175_fu_663_p2;
        add_ln176_reg_1300 <= add_ln176_fu_677_p2;
        and_ln180_1_reg_1348 <= and_ln180_1_fu_751_p2;
        and_ln180_reg_1319 <= and_ln180_fu_695_p2;
        hit_x_reg_1252 <= stack_x_q0;
        hit_y_reg_1270 <= stack_y_q0;
        icmp_ln180_1_reg_1314 <= icmp_ln180_1_fu_689_p2;
        icmp_ln180_3_reg_1343 <= icmp_ln180_3_fu_745_p2;
        icmp_ln180_reg_1308 <= icmp_ln180_fu_683_p2;
        trunc_ln170_1_reg_1265 <= trunc_ln170_1_fu_659_p1;
        trunc_ln170_reg_1260 <= trunc_ln170_fu_655_p1;
        trunc_ln176_1_reg_1294 <= trunc_ln176_1_fu_673_p1;
        trunc_ln176_reg_1288 <= trunc_ln176_fu_669_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln168_reg_1231 == 1'd1))) begin
        add_ln176_1_reg_1498 <= add_ln176_1_fu_971_p2;
        and_ln180_4_reg_1474 <= and_ln180_4_fu_926_p2;
        and_ln180_5_reg_1505 <= and_ln180_5_fu_982_p2;
        and_ln180_6_reg_1529 <= and_ln180_6_fu_1029_p2;
        and_ln180_7_reg_1538 <= and_ln180_7_fu_1068_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_6_fu_1029_p2) & (icmp_ln168_reg_1231 == 1'd1))) begin
        add_ln184_13_reg_1533 <= add_ln184_13_fu_1062_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_7_fu_1068_p2) & (icmp_ln168_reg_1231 == 1'd1))) begin
        add_ln184_15_reg_1542 <= add_ln184_15_fu_1101_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1))) begin
        add_ln186_2_reg_1619 <= add_ln186_2_fu_1140_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln180_fu_695_p2) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state3) & (grp_fu_605_p2 == 1'd1) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        ap_phi_reg_pp0_iter0_stackIndex_5_0_reg_474 <= stackIndex_2_reg_1235;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln180_2_reg_1405) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_fu_605_p2 == 1'd1) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        ap_phi_reg_pp0_iter0_stackIndex_5_2_reg_505 <= ap_phi_mux_stackIndex_5_1_phi_fu_491_p8;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln184_3_reg_1470 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'd0 == and_ln180_3_reg_1434) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_3_reg_1470 == 1'd0) & (grp_fu_623_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        ap_phi_reg_pp0_iter0_stackIndex_5_3_reg_522 <= ap_phi_mux_stackIndex_5_2_phi_fu_508_p8;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln184_12_reg_1603 == 1'd0) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_4_reg_1555 == 1'd1) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'd0 == and_ln180_4_reg_1474) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        ap_phi_reg_pp0_iter0_stackIndex_5_4_reg_539 <= ap_phi_mux_stackIndex_5_3_phi_fu_525_p8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln180_1_fu_751_p2))) begin
        clusterGrid_clusterID_addr_1_reg_1367 <= zext_ln184_3_fu_793_p1;
        clusterGrid_x_addr_1_reg_1357 <= zext_ln184_3_fu_793_p1;
        clusterGrid_y_addr_1_reg_1362 <= zext_ln184_3_fu_793_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln180_2_fu_820_p2) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_clusterID_addr_2_reg_1424 <= zext_ln184_5_fu_860_p1;
        clusterGrid_x_addr_2_reg_1414 <= zext_ln184_5_fu_860_p1;
        clusterGrid_y_addr_2_reg_1419 <= zext_ln184_5_fu_860_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln180_3_fu_873_p2) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_clusterID_addr_3_reg_1453 <= zext_ln184_7_fu_911_p1;
        clusterGrid_x_addr_3_reg_1443 <= zext_ln184_7_fu_911_p1;
        clusterGrid_y_addr_3_reg_1448 <= zext_ln184_7_fu_911_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_4_fu_926_p2) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_clusterID_addr_4_reg_1493 <= zext_ln184_9_fu_963_p1;
        clusterGrid_x_addr_4_reg_1483 <= zext_ln184_9_fu_963_p1;
        clusterGrid_y_addr_4_reg_1488 <= zext_ln184_9_fu_963_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_5_fu_982_p2) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_clusterID_addr_5_reg_1524 <= zext_ln184_11_fu_1021_p1;
        clusterGrid_x_addr_5_reg_1514 <= zext_ln184_11_fu_1021_p1;
        clusterGrid_y_addr_5_reg_1519 <= zext_ln184_11_fu_1021_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_clusterID_addr_6_reg_1578 <= zext_ln184_13_fu_1120_p1;
        clusterGrid_x_addr_6_reg_1568 <= zext_ln184_13_fu_1120_p1;
        clusterGrid_y_addr_6_reg_1573 <= zext_ln184_13_fu_1120_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_clusterID_addr_7_reg_1598 <= zext_ln184_15_fu_1127_p1;
        clusterGrid_x_addr_7_reg_1588 <= zext_ln184_15_fu_1127_p1;
        clusterGrid_y_addr_7_reg_1593 <= zext_ln184_15_fu_1127_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln180_fu_695_p2))) begin
        clusterGrid_clusterID_addr_reg_1338 <= zext_ln184_1_fu_737_p1;
        clusterGrid_x_addr_reg_1328 <= zext_ln184_1_fu_737_p1;
        clusterGrid_y_addr_reg_1333 <= zext_ln184_1_fu_737_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        icmp_ln168_reg_1231 <= icmp_ln168_fu_637_p2;
        stackIndex_1_reg_1226 <= ap_sig_allocacmp_stackIndex_1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_10_reg_1547 <= grp_fu_617_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_11_reg_1551 <= grp_fu_623_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_12_reg_1603 <= grp_fu_617_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln184_5_reg_1559 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_13_reg_1607 <= grp_fu_623_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_14_reg_1624 <= grp_fu_617_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_15_reg_1628 <= grp_fu_623_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_1_reg_1458 <= grp_fu_617_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_2_reg_1466 <= grp_fu_605_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_3_reg_1470 <= grp_fu_611_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_4_reg_1555 <= grp_fu_605_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_5_reg_1559 <= grp_fu_611_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_6_reg_1611 <= grp_fu_605_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_7_reg_1615 <= grp_fu_611_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_8_reg_1376 <= grp_fu_611_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_9_reg_1462 <= grp_fu_623_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1))) begin
        icmp_ln184_reg_1372 <= grp_fu_605_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln168_fu_637_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        stackIndex_2_reg_1235 <= stackIndex_2_fu_643_p2;
        stack_x_addr_reg_1242 <= zext_ln170_fu_649_p1;
        stack_y_addr_reg_1247 <= zext_ln170_fu_649_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln168_fu_637_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_254)) begin
        if ((grp_fu_617_p2 == 1'd0)) begin
            ap_phi_mux_stackIndex_5_0_phi_fu_477_p8 = stackIndex_2_reg_1235;
        end else if ((grp_fu_617_p2 == 1'd1)) begin
            ap_phi_mux_stackIndex_5_0_phi_fu_477_p8 = stackIndex_1_reg_1226;
        end else begin
            ap_phi_mux_stackIndex_5_0_phi_fu_477_p8 = ap_phi_reg_pp0_iter0_stackIndex_5_0_reg_474;
        end
    end else begin
        ap_phi_mux_stackIndex_5_0_phi_fu_477_p8 = ap_phi_reg_pp0_iter0_stackIndex_5_0_reg_474;
    end
end

always @ (*) begin
    if ((((grp_fu_623_p2 == 1'd0) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_8_reg_1376 == 1'd1) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'd0 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        ap_phi_mux_stackIndex_5_1_phi_fu_491_p8 = ap_phi_mux_stackIndex_5_0_phi_fu_477_p8;
    end else if (((grp_fu_623_p2 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1))) begin
        ap_phi_mux_stackIndex_5_1_phi_fu_491_p8 = add_ln186_fu_919_p2;
    end else begin
        ap_phi_mux_stackIndex_5_1_phi_fu_491_p8 = ap_phi_reg_pp0_iter0_stackIndex_5_1_reg_488;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_320)) begin
        if ((grp_fu_617_p2 == 1'd0)) begin
            ap_phi_mux_stackIndex_5_2_phi_fu_508_p8 = stackIndex_5_1_reg_488;
        end else if ((grp_fu_617_p2 == 1'd1)) begin
            ap_phi_mux_stackIndex_5_2_phi_fu_508_p8 = add_ln186_1_fu_1113_p2;
        end else begin
            ap_phi_mux_stackIndex_5_2_phi_fu_508_p8 = ap_phi_reg_pp0_iter0_stackIndex_5_2_reg_505;
        end
    end else begin
        ap_phi_mux_stackIndex_5_2_phi_fu_508_p8 = ap_phi_reg_pp0_iter0_stackIndex_5_2_reg_505;
    end
end

always @ (*) begin
    if (((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1))) begin
        ap_phi_mux_stackIndex_5_3_phi_fu_525_p8 = add_ln186_2_reg_1619;
    end else begin
        ap_phi_mux_stackIndex_5_3_phi_fu_525_p8 = ap_phi_reg_pp0_iter0_stackIndex_5_3_reg_522;
    end
end

always @ (*) begin
    if (((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1))) begin
        ap_phi_mux_stackIndex_5_4_phi_fu_542_p8 = add_ln186_3_fu_1158_p2;
    end else begin
        ap_phi_mux_stackIndex_5_4_phi_fu_542_p8 = ap_phi_reg_pp0_iter0_stackIndex_5_4_reg_539;
    end
end

always @ (*) begin
    if ((((icmp_ln184_15_reg_1628 == 1'd0) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_7_reg_1615 == 1'd1) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'd0 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        ap_phi_mux_stackIndex_5_7_phi_fu_592_p8 = ap_phi_reg_pp0_iter0_stackIndex_5_6_reg_573;
    end else if (((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1))) begin
        ap_phi_mux_stackIndex_5_7_phi_fu_592_p8 = add_ln186_6_fu_1189_p2;
    end else begin
        ap_phi_mux_stackIndex_5_7_phi_fu_592_p8 = ap_phi_reg_pp0_iter0_stackIndex_5_7_reg_589;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_stackIndex_1 = stackIndex_3;
    end else begin
        ap_sig_allocacmp_stackIndex_1 = stackIndex_fu_52;
    end
end

always @ (*) begin
    if ((((grp_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_address0 = clusterGrid_clusterID_addr_7_reg_1598;
    end else if ((((grp_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_address0 = clusterGrid_clusterID_addr_5_reg_1524;
    end else if ((((grp_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_address0 = clusterGrid_clusterID_addr_3_reg_1453;
    end else if ((((grp_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_9_reg_1462 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_address0 = clusterGrid_clusterID_addr_1_reg_1367;
    end else begin
        clusterGrid_clusterID_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state6) & (grp_fu_605_p2 == 1'd0) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_address1 = clusterGrid_clusterID_addr_6_reg_1578;
    end else if ((((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (grp_fu_605_p2 == 1'd0) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_address1 = clusterGrid_clusterID_addr_4_reg_1493;
    end else if ((((icmp_ln184_10_reg_1547 == 1'd1) & (icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_fu_605_p2 == 1'd0) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_address1 = clusterGrid_clusterID_addr_2_reg_1424;
    end else if ((((icmp_ln184_1_reg_1458 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (grp_fu_605_p2 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_address1 = clusterGrid_clusterID_addr_reg_1338;
    end else begin
        clusterGrid_clusterID_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((grp_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((grp_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((grp_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)) | ((grp_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_9_reg_1462 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 
    == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_ce0 = 1'b1;
    end else begin
        clusterGrid_clusterID_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln184_1_reg_1458 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_10_reg_1547 == 1'd1) & (icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state6) & (grp_fu_605_p2 == 1'd0) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (grp_fu_605_p2 == 1'd0) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_fu_605_p2 == 1'd0) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 
    == ap_CS_fsm_state3) & (grp_fu_605_p2 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_ce1 = 1'b1;
    end else begin
        clusterGrid_clusterID_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln184_9_reg_1462 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_we0 = 1'b1;
    end else begin
        clusterGrid_clusterID_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln184_1_reg_1458 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_10_reg_1547 == 1'd1) & (icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_clusterID_we1 = 1'b1;
    end else begin
        clusterGrid_clusterID_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fu_623_p2 == 1'd1) & (icmp_ln168_reg_1231 == 1'd1))) begin
        if ((1'b1 == ap_condition_1102)) begin
            clusterGrid_x_address0 = clusterGrid_x_addr_7_reg_1588;
        end else if ((1'b1 == ap_condition_1098)) begin
            clusterGrid_x_address0 = clusterGrid_x_addr_5_reg_1514;
        end else if ((1'b1 == ap_condition_1094)) begin
            clusterGrid_x_address0 = clusterGrid_x_addr_3_reg_1443;
        end else if ((1'b1 == ap_condition_1090)) begin
            clusterGrid_x_address0 = clusterGrid_x_addr_1_reg_1357;
        end else begin
            clusterGrid_x_address0 = 'bx;
        end
    end else begin
        clusterGrid_x_address0 = 'bx;
    end
end

always @ (*) begin
    if (((grp_fu_617_p2 == 1'd1) & (icmp_ln168_reg_1231 == 1'd1))) begin
        if ((1'b1 == ap_condition_1119)) begin
            clusterGrid_x_address1 = clusterGrid_x_addr_6_reg_1568;
        end else if ((1'b1 == ap_condition_1115)) begin
            clusterGrid_x_address1 = clusterGrid_x_addr_4_reg_1483;
        end else if ((1'b1 == ap_condition_1111)) begin
            clusterGrid_x_address1 = clusterGrid_x_addr_2_reg_1414;
        end else if ((1'b1 == ap_condition_1107)) begin
            clusterGrid_x_address1 = clusterGrid_x_addr_reg_1328;
        end else begin
            clusterGrid_x_address1 = 'bx;
        end
    end else begin
        clusterGrid_x_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((grp_fu_623_p2 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_7_reg_1615 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_5_reg_1559 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_3_reg_1470 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_x_ce0 = 1'b1;
    end else begin
        clusterGrid_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_6_reg_1611 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_4_reg_1555 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_2_reg_1466 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_x_ce1 = 1'b1;
    end else begin
        clusterGrid_x_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln184_7_reg_1615 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_x_d0 = add_ln175_1_reg_1380;
    end else if ((((icmp_ln184_5_reg_1559 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_3_reg_1470 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_x_d0 = add_ln175_reg_1281;
    end else if (((grp_fu_623_p2 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_x_d0 = hit_x_reg_1252;
    end else begin
        clusterGrid_x_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln184_6_reg_1611 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_x_d1 = hit_x_reg_1252;
    end else if ((((icmp_ln184_4_reg_1555 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_2_reg_1466 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_x_d1 = add_ln175_1_reg_1380;
    end else if (((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_x_d1 = add_ln175_reg_1281;
    end else begin
        clusterGrid_x_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((grp_fu_623_p2 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_7_reg_1615 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_5_reg_1559 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_3_reg_1470 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_x_we0 = 1'b1;
    end else begin
        clusterGrid_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_6_reg_1611 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_4_reg_1555 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_2_reg_1466 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_x_we1 = 1'b1;
    end else begin
        clusterGrid_x_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fu_623_p2 == 1'd1) & (icmp_ln168_reg_1231 == 1'd1))) begin
        if ((1'b1 == ap_condition_1102)) begin
            clusterGrid_y_address0 = clusterGrid_y_addr_7_reg_1593;
        end else if ((1'b1 == ap_condition_1098)) begin
            clusterGrid_y_address0 = clusterGrid_y_addr_5_reg_1519;
        end else if ((1'b1 == ap_condition_1094)) begin
            clusterGrid_y_address0 = clusterGrid_y_addr_3_reg_1448;
        end else if ((1'b1 == ap_condition_1090)) begin
            clusterGrid_y_address0 = clusterGrid_y_addr_1_reg_1362;
        end else begin
            clusterGrid_y_address0 = 'bx;
        end
    end else begin
        clusterGrid_y_address0 = 'bx;
    end
end

always @ (*) begin
    if (((grp_fu_617_p2 == 1'd1) & (icmp_ln168_reg_1231 == 1'd1))) begin
        if ((1'b1 == ap_condition_1119)) begin
            clusterGrid_y_address1 = clusterGrid_y_addr_6_reg_1573;
        end else if ((1'b1 == ap_condition_1115)) begin
            clusterGrid_y_address1 = clusterGrid_y_addr_4_reg_1488;
        end else if ((1'b1 == ap_condition_1111)) begin
            clusterGrid_y_address1 = clusterGrid_y_addr_2_reg_1419;
        end else if ((1'b1 == ap_condition_1107)) begin
            clusterGrid_y_address1 = clusterGrid_y_addr_reg_1333;
        end else begin
            clusterGrid_y_address1 = 'bx;
        end
    end else begin
        clusterGrid_y_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((grp_fu_623_p2 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_7_reg_1615 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_5_reg_1559 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_3_reg_1470 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_y_ce0 = 1'b1;
    end else begin
        clusterGrid_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_6_reg_1611 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_4_reg_1555 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_2_reg_1466 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_y_ce1 = 1'b1;
    end else begin
        clusterGrid_y_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln184_7_reg_1615 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_5_reg_1559 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_y_d0 = add_ln176_1_reg_1498;
    end else if (((icmp_ln184_3_reg_1470 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_y_d0 = hit_y_reg_1270;
    end else if (((grp_fu_623_p2 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_y_d0 = add_ln176_reg_1300;
    end else begin
        clusterGrid_y_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln184_6_reg_1611 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_y_d1 = add_ln176_1_reg_1498;
    end else if (((icmp_ln184_4_reg_1555 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1))) begin
        clusterGrid_y_d1 = hit_y_reg_1270;
    end else if ((((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_2_reg_1466 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_y_d1 = add_ln176_reg_1300;
    end else begin
        clusterGrid_y_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((grp_fu_623_p2 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_7_reg_1615 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_5_reg_1559 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_3_reg_1470 == 1'd0) & (grp_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_y_we0 = 1'b1;
    end else begin
        clusterGrid_y_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_6_reg_1611 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_4_reg_1555 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_2_reg_1466 == 1'd0) & (grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        clusterGrid_y_we1 = 1'b1;
    end else begin
        clusterGrid_y_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1))) begin
        grid_address0 = zext_ln184_15_fu_1127_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_5_fu_982_p2) & (icmp_ln168_reg_1231 == 1'd1))) begin
        grid_address0 = zext_ln184_11_fu_1021_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln180_3_fu_873_p2) & (icmp_ln168_reg_1231 == 1'd1))) begin
        grid_address0 = zext_ln184_7_fu_911_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln180_1_fu_751_p2))) begin
        grid_address0 = zext_ln184_3_fu_793_p1;
    end else begin
        grid_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1))) begin
        grid_address1 = zext_ln184_13_fu_1120_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_4_fu_926_p2) & (icmp_ln168_reg_1231 == 1'd1))) begin
        grid_address1 = zext_ln184_9_fu_963_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln180_2_fu_820_p2) & (icmp_ln168_reg_1231 == 1'd1))) begin
        grid_address1 = zext_ln184_5_fu_860_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln180_fu_695_p2))) begin
        grid_address1 = zext_ln184_1_fu_737_p1;
    end else begin
        grid_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_5_fu_982_p2) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln180_3_fu_873_p2) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln180_1_fu_751_p2)))) begin
        grid_ce0 = 1'b1;
    end else begin
        grid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_4_fu_926_p2) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln180_2_fu_820_p2) & (icmp_ln168_reg_1231 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln180_fu_695_p2)))) begin
        grid_ce1 = 1'b1;
    end else begin
        grid_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln168_fu_637_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        stackIndex_2_out_ap_vld = 1'b1;
    end else begin
        stackIndex_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_x_address0 = zext_ln186_6_fu_1196_p1;
    end else if (((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_x_address0 = zext_ln186_5_fu_1183_p1;
    end else if (((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_x_address0 = zext_ln186_4_fu_1171_p1;
    end else if (((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_x_address0 = zext_ln186_3_fu_1152_p1;
    end else if (((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_x_address0 = zext_ln186_2_fu_1146_p1;
    end else if (((icmp_ln184_10_reg_1547 == 1'd1) & (icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_x_address0 = zext_ln186_1_fu_1134_p1;
    end else if (((icmp_ln184_9_reg_1462 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_x_address0 = zext_ln186_fu_1107_p1;
    end else if (((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_x_address0 = stack_x_addr_reg_1242;
    end else if (((icmp_ln168_fu_637_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        stack_x_address0 = zext_ln170_fu_649_p1;
    end else begin
        stack_x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln184_10_reg_1547 == 1'd1) & (icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_9_reg_1462 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 
    == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln168_fu_637_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1)))) begin
        stack_x_ce0 = 1'b1;
    end else begin
        stack_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln184_10_reg_1547 == 1'd1) & (icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        stack_x_d0 = add_ln175_1_reg_1380;
    end else if ((((icmp_ln184_9_reg_1462 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        stack_x_d0 = hit_x_reg_1252;
    end else if ((((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        stack_x_d0 = add_ln175_reg_1281;
    end else begin
        stack_x_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln184_10_reg_1547 == 1'd1) & (icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_9_reg_1462 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 
    == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        stack_x_we0 = 1'b1;
    end else begin
        stack_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_y_address0 = zext_ln186_6_fu_1196_p1;
    end else if (((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_y_address0 = zext_ln186_5_fu_1183_p1;
    end else if (((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_y_address0 = zext_ln186_4_fu_1171_p1;
    end else if (((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_y_address0 = zext_ln186_3_fu_1152_p1;
    end else if (((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_y_address0 = zext_ln186_2_fu_1146_p1;
    end else if (((icmp_ln184_10_reg_1547 == 1'd1) & (icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_y_address0 = zext_ln186_1_fu_1134_p1;
    end else if (((icmp_ln184_9_reg_1462 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_y_address0 = zext_ln186_fu_1107_p1;
    end else if (((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1))) begin
        stack_y_address0 = stack_y_addr_reg_1247;
    end else if (((icmp_ln168_fu_637_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        stack_y_address0 = zext_ln170_fu_649_p1;
    end else begin
        stack_y_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln184_10_reg_1547 == 1'd1) & (icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_9_reg_1462 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 
    == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln168_fu_637_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1)))) begin
        stack_y_ce0 = 1'b1;
    end else begin
        stack_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        stack_y_d0 = add_ln176_1_reg_1498;
    end else if ((((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        stack_y_d0 = hit_y_reg_1270;
    end else if ((((icmp_ln184_10_reg_1547 == 1'd1) & (icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_9_reg_1462 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        stack_y_d0 = add_ln176_reg_1300;
    end else begin
        stack_y_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln184_10_reg_1547 == 1'd1) & (icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_9_reg_1462 == 1'd1) & (icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_1_reg_1348) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_15_reg_1628 == 1'd1) & (icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (1'd1 == and_ln180_7_reg_1538) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_12_reg_1603 == 1'd1) & (icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln180_4_reg_1474) & (icmp_ln168_reg_1231 == 1'd1)) | ((grp_fu_617_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_14_reg_1624 == 1'd1) & (icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln180_6_reg_1529) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_13_reg_1607 == 1'd1) & (icmp_ln184_5_reg_1559 
    == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln180_5_reg_1505) & (icmp_ln168_reg_1231 == 1'd1)) | ((icmp_ln184_11_reg_1551 == 1'd1) & (icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_3_reg_1434) & (icmp_ln168_reg_1231 == 1'd1)))) begin
        stack_y_we0 = 1'b1;
    end else begin
        stack_y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln168_fu_637_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln175_1_fu_801_p2 = (hit_x_reg_1252 + 32'd1);

assign add_ln175_fu_663_p2 = ($signed(stack_x_q0) + $signed(32'd4294967295));

assign add_ln176_1_fu_971_p2 = (hit_y_reg_1270 + 32'd1);

assign add_ln176_fu_677_p2 = ($signed(stack_y_q0) + $signed(32'd4294967295));

assign add_ln184_10_fu_1001_p2 = (tmp_10_fu_987_p3 + tmp_11_fu_994_p3);

assign add_ln184_11_fu_1015_p2 = (add_ln184_10_fu_1001_p2 + zext_ln184_10_fu_1011_p1);

assign add_ln184_12_fu_1048_p2 = (tmp_12_fu_1034_p3 + tmp_13_fu_1041_p3);

assign add_ln184_13_fu_1062_p2 = (add_ln184_12_fu_1048_p2 + zext_ln184_12_fu_1058_p1);

assign add_ln184_14_fu_1087_p2 = (tmp_14_fu_1073_p3 + tmp_15_fu_1080_p3);

assign add_ln184_15_fu_1101_p2 = (add_ln184_14_fu_1087_p2 + zext_ln184_14_fu_1097_p1);

assign add_ln184_1_fu_731_p2 = (add_ln184_fu_717_p2 + zext_ln184_fu_727_p1);

assign add_ln184_2_fu_773_p2 = (tmp_s_fu_757_p3 + tmp_1_fu_765_p3);

assign add_ln184_3_fu_787_p2 = (add_ln184_2_fu_773_p2 + zext_ln184_2_fu_783_p1);

assign add_ln184_4_fu_841_p2 = (tmp_2_fu_825_p3 + tmp_3_fu_833_p3);

assign add_ln184_5_fu_854_p2 = (add_ln184_4_fu_841_p2 + zext_ln184_4_fu_850_p1);

assign add_ln184_6_fu_892_p2 = (tmp_4_fu_878_p3 + tmp_5_fu_885_p3);

assign add_ln184_7_fu_905_p2 = (add_ln184_6_fu_892_p2 + zext_ln184_6_fu_901_p1);

assign add_ln184_8_fu_944_p2 = (tmp_6_fu_930_p3 + tmp_7_fu_937_p3);

assign add_ln184_9_fu_957_p2 = (add_ln184_8_fu_944_p2 + zext_ln184_8_fu_953_p1);

assign add_ln184_fu_717_p2 = (tmp_8_fu_701_p3 + tmp_9_fu_709_p3);

assign add_ln186_1_fu_1113_p2 = (stackIndex_5_1_reg_488 + 32'd1);

assign add_ln186_2_fu_1140_p2 = (stackIndex_5_2_reg_505 + 32'd1);

assign add_ln186_3_fu_1158_p2 = (stackIndex_5_3_reg_522 + 32'd1);

assign add_ln186_4_fu_1165_p2 = (ap_phi_mux_stackIndex_5_4_phi_fu_542_p8 + 32'd1);

assign add_ln186_5_fu_1177_p2 = (ap_phi_reg_pp0_iter0_stackIndex_5_5_reg_556 + 32'd1);

assign add_ln186_6_fu_1189_p2 = (ap_phi_reg_pp0_iter0_stackIndex_5_6_reg_573 + 32'd1);

assign add_ln186_fu_919_p2 = (ap_phi_mux_stackIndex_5_0_phi_fu_477_p8 + 32'd1);

assign and_ln180_1_fu_751_p2 = (icmp_ln180_3_fu_745_p2 & icmp_ln180_1_fu_689_p2);

assign and_ln180_2_fu_820_p2 = (icmp_ln180_2_fu_814_p2 & icmp_ln180_1_reg_1314);

assign and_ln180_3_fu_873_p2 = (icmp_ln180_reg_1308 & icmp_ln180_4_fu_868_p2);

assign and_ln180_4_fu_926_p2 = (icmp_ln180_4_reg_1429 & icmp_ln180_2_reg_1399);

assign and_ln180_5_fu_982_p2 = (icmp_ln180_reg_1308 & icmp_ln180_5_fu_976_p2);

assign and_ln180_6_fu_1029_p2 = (icmp_ln180_5_fu_976_p2 & icmp_ln180_3_reg_1343);

assign and_ln180_7_fu_1068_p2 = (icmp_ln180_5_fu_976_p2 & icmp_ln180_2_reg_1399);

assign and_ln180_fu_695_p2 = (icmp_ln180_fu_683_p2 & icmp_ln180_1_fu_689_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_state10_pp0_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage10_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1090 = ((icmp_ln184_8_reg_1376 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln180_1_reg_1348));
end

always @ (*) begin
    ap_condition_1094 = ((icmp_ln184_3_reg_1470 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_3_reg_1434));
end

always @ (*) begin
    ap_condition_1098 = ((icmp_ln184_5_reg_1559 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_5_reg_1505));
end

always @ (*) begin
    ap_condition_1102 = ((icmp_ln184_7_reg_1615 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_7_reg_1538));
end

always @ (*) begin
    ap_condition_1107 = ((1'b1 == ap_CS_fsm_state4) & (icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319));
end

always @ (*) begin
    ap_condition_1111 = ((icmp_ln184_2_reg_1466 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'd1 == and_ln180_2_reg_1405));
end

always @ (*) begin
    ap_condition_1115 = ((icmp_ln184_4_reg_1555 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln180_4_reg_1474));
end

always @ (*) begin
    ap_condition_1119 = ((icmp_ln184_6_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln180_6_reg_1529));
end

always @ (*) begin
    ap_condition_254 = ((icmp_ln184_reg_1372 == 1'd0) & (1'd1 == and_ln180_reg_1319) & (icmp_ln168_reg_1231 == 1'd1));
end

always @ (*) begin
    ap_condition_320 = ((icmp_ln184_2_reg_1466 == 1'd0) & (1'd1 == and_ln180_2_reg_1405) & (icmp_ln168_reg_1231 == 1'd1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_stackIndex_5_1_reg_488 = 'bx;

assign ap_phi_reg_pp0_iter0_stackIndex_5_7_reg_589 = 'bx;

assign clusterGrid_clusterID_d0 = clusterID_3;

assign clusterGrid_clusterID_d1 = clusterID_3;

assign grp_fu_605_p2 = ((grid_q1 == 32'd0) ? 1'b1 : 1'b0);

assign grp_fu_611_p2 = ((grid_q0 == 32'd0) ? 1'b1 : 1'b0);

assign grp_fu_617_p2 = ((clusterGrid_clusterID_q1 == 32'd0) ? 1'b1 : 1'b0);

assign grp_fu_623_p2 = ((clusterGrid_clusterID_q0 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_637_p2 = (($signed(ap_sig_allocacmp_stackIndex_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln180_1_fu_689_p2 = ((add_ln176_fu_677_p2 < 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln180_2_fu_814_p2 = ((add_ln175_1_fu_801_p2 < 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln180_3_fu_745_p2 = ((stack_x_q0 < 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln180_4_fu_868_p2 = ((hit_y_reg_1270 < 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln180_5_fu_976_p2 = ((add_ln176_1_fu_971_p2 < 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln180_fu_683_p2 = ((add_ln175_fu_663_p2 < 32'd10) ? 1'b1 : 1'b0);

assign stackIndex_2_fu_643_p2 = ($signed(ap_sig_allocacmp_stackIndex_1) + $signed(32'd4294967295));

assign stackIndex_2_out = ap_sig_allocacmp_stackIndex_1;

assign tmp_10_fu_987_p3 = {{trunc_ln176_1_reg_1294}, {3'd0}};

assign tmp_11_fu_994_p3 = {{trunc_ln176_reg_1288}, {1'd0}};

assign tmp_12_fu_1034_p3 = {{trunc_ln170_1_reg_1265}, {3'd0}};

assign tmp_13_fu_1041_p3 = {{trunc_ln170_reg_1260}, {1'd0}};

assign tmp_14_fu_1073_p3 = {{trunc_ln180_1_reg_1393}, {3'd0}};

assign tmp_15_fu_1080_p3 = {{trunc_ln180_reg_1387}, {1'd0}};

assign tmp_1_fu_765_p3 = {{trunc_ln170_fu_655_p1}, {1'd0}};

assign tmp_2_fu_825_p3 = {{trunc_ln180_1_fu_810_p1}, {3'd0}};

assign tmp_3_fu_833_p3 = {{trunc_ln180_fu_806_p1}, {1'd0}};

assign tmp_4_fu_878_p3 = {{trunc_ln176_1_reg_1294}, {3'd0}};

assign tmp_5_fu_885_p3 = {{trunc_ln176_reg_1288}, {1'd0}};

assign tmp_6_fu_930_p3 = {{trunc_ln180_1_reg_1393}, {3'd0}};

assign tmp_7_fu_937_p3 = {{trunc_ln180_reg_1387}, {1'd0}};

assign tmp_8_fu_701_p3 = {{trunc_ln176_1_fu_673_p1}, {3'd0}};

assign tmp_9_fu_709_p3 = {{trunc_ln176_fu_669_p1}, {1'd0}};

assign tmp_s_fu_757_p3 = {{trunc_ln170_1_fu_659_p1}, {3'd0}};

assign trunc_ln170_1_fu_659_p1 = stack_x_q0[3:0];

assign trunc_ln170_fu_655_p1 = stack_x_q0[5:0];

assign trunc_ln176_1_fu_673_p1 = add_ln175_fu_663_p2[3:0];

assign trunc_ln176_fu_669_p1 = add_ln175_fu_663_p2[5:0];

assign trunc_ln180_1_fu_810_p1 = add_ln175_1_fu_801_p2[3:0];

assign trunc_ln180_fu_806_p1 = add_ln175_1_fu_801_p2[5:0];

assign trunc_ln184_1_fu_779_p1 = add_ln176_fu_677_p2[3:0];

assign trunc_ln184_2_fu_847_p1 = add_ln176_reg_1300[3:0];

assign trunc_ln184_3_fu_898_p1 = hit_y_reg_1270[3:0];

assign trunc_ln184_4_fu_950_p1 = hit_y_reg_1270[3:0];

assign trunc_ln184_5_fu_1007_p1 = add_ln176_1_fu_971_p2[3:0];

assign trunc_ln184_6_fu_1054_p1 = add_ln176_1_fu_971_p2[3:0];

assign trunc_ln184_7_fu_1093_p1 = add_ln176_1_fu_971_p2[3:0];

assign trunc_ln184_fu_723_p1 = add_ln176_fu_677_p2[3:0];

assign zext_ln170_fu_649_p1 = stackIndex_2_fu_643_p2;

assign zext_ln184_10_fu_1011_p1 = trunc_ln184_5_fu_1007_p1;

assign zext_ln184_11_fu_1021_p1 = add_ln184_11_fu_1015_p2;

assign zext_ln184_12_fu_1058_p1 = trunc_ln184_6_fu_1054_p1;

assign zext_ln184_13_fu_1120_p1 = add_ln184_13_reg_1533;

assign zext_ln184_14_fu_1097_p1 = trunc_ln184_7_fu_1093_p1;

assign zext_ln184_15_fu_1127_p1 = add_ln184_15_reg_1542;

assign zext_ln184_1_fu_737_p1 = add_ln184_1_fu_731_p2;

assign zext_ln184_2_fu_783_p1 = trunc_ln184_1_fu_779_p1;

assign zext_ln184_3_fu_793_p1 = add_ln184_3_fu_787_p2;

assign zext_ln184_4_fu_850_p1 = trunc_ln184_2_fu_847_p1;

assign zext_ln184_5_fu_860_p1 = add_ln184_5_fu_854_p2;

assign zext_ln184_6_fu_901_p1 = trunc_ln184_3_fu_898_p1;

assign zext_ln184_7_fu_911_p1 = add_ln184_7_fu_905_p2;

assign zext_ln184_8_fu_953_p1 = trunc_ln184_4_fu_950_p1;

assign zext_ln184_9_fu_963_p1 = add_ln184_9_fu_957_p2;

assign zext_ln184_fu_727_p1 = trunc_ln184_fu_723_p1;

assign zext_ln186_1_fu_1134_p1 = stackIndex_5_1_reg_488;

assign zext_ln186_2_fu_1146_p1 = stackIndex_5_2_reg_505;

assign zext_ln186_3_fu_1152_p1 = ap_phi_mux_stackIndex_5_3_phi_fu_525_p8;

assign zext_ln186_4_fu_1171_p1 = ap_phi_mux_stackIndex_5_4_phi_fu_542_p8;

assign zext_ln186_5_fu_1183_p1 = ap_phi_reg_pp0_iter0_stackIndex_5_5_reg_556;

assign zext_ln186_6_fu_1196_p1 = ap_phi_reg_pp0_iter0_stackIndex_5_6_reg_573;

assign zext_ln186_fu_1107_p1 = stackIndex_5_0_reg_474;

endmodule //naive_findClustersHLS1_naive_findClustersHLS1_Pipeline_VITIS_LOOP_168_3
