// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="naive_findClustersHLS2_naive_findClustersHLS2,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.002000,HLS_SYN_LAT=1656,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=368,HLS_SYN_LUT=1746,HLS_VERSION=2023_1}" *)

module naive_findClustersHLS2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        grid_address0,
        grid_ce0,
        grid_q0,
        pointsGrid_address0,
        pointsGrid_ce0,
        pointsGrid_we0,
        pointsGrid_d0
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] grid_address0;
output   grid_ce0;
input  [0:0] grid_q0;
output  [7:0] pointsGrid_address0;
output   pointsGrid_ce0;
output   pointsGrid_we0;
output  [95:0] pointsGrid_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] grid_address0;
reg grid_ce0;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] clusterGrid1_address0;
reg    clusterGrid1_ce0;
wire   [15:0] clusterGrid1_q0;
reg   [7:0] clusterGrid1_address1;
reg    clusterGrid1_ce1;
reg    clusterGrid1_we1;
reg   [15:0] clusterGrid1_d1;
wire   [15:0] clusterGrid1_q1;
reg    clusterGrid2_ce0;
wire   [15:0] clusterGrid2_q0;
reg   [7:0] clusterGrid2_address1;
reg    clusterGrid2_ce1;
reg    clusterGrid2_we1;
reg   [15:0] clusterGrid2_d1;
wire    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start;
wire    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done;
wire    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_idle;
wire    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_ready;
wire   [7:0] grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_address0;
wire    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_ce0;
wire   [7:0] grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address0;
wire    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce0;
wire   [7:0] grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address1;
wire    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce1;
wire    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_we1;
wire   [15:0] grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_d1;
wire    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start;
wire    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_done;
wire    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_idle;
wire    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_ready;
wire   [7:0] grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_address0;
wire    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_ce0;
wire   [7:0] grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address0;
wire    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce0;
wire   [7:0] grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address1;
wire    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce1;
wire   [7:0] grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_address1;
wire    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_ce1;
wire    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_we1;
wire   [15:0] grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_d1;
wire    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start;
wire    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done;
wire    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_idle;
wire    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_ready;
wire   [7:0] grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_address0;
wire    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_ce0;
wire   [7:0] grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_address0;
wire    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_ce0;
wire    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_we0;
wire   [95:0] grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_d0;
wire   [7:0] grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_address0;
wire    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_ce0;
wire   [7:0] grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_address0;
wire    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_ce0;
reg    grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg = 1'b0;
#0 grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg = 1'b0;
#0 grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg = 1'b0;
end

naive_findClustersHLS2_clusterGrid1_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 144 ),
    .AddressWidth( 8 ))
clusterGrid1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(clusterGrid1_address0),
    .ce0(clusterGrid1_ce0),
    .q0(clusterGrid1_q0),
    .address1(clusterGrid1_address1),
    .ce1(clusterGrid1_ce1),
    .we1(clusterGrid1_we1),
    .d1(clusterGrid1_d1),
    .q1(clusterGrid1_q1)
);

naive_findClustersHLS2_clusterGrid2_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 144 ),
    .AddressWidth( 8 ))
clusterGrid2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_address0),
    .ce0(clusterGrid2_ce0),
    .q0(clusterGrid2_q0),
    .address1(clusterGrid2_address1),
    .ce1(clusterGrid2_ce1),
    .we1(clusterGrid2_we1),
    .d1(clusterGrid2_d1)
);

naive_findClustersHLS2_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start),
    .ap_done(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done),
    .ap_idle(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_idle),
    .ap_ready(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_ready),
    .grid_address0(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_address0),
    .grid_ce0(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_ce0),
    .grid_q0(grid_q0),
    .clusterGrid1_address0(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address0),
    .clusterGrid1_ce0(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce0),
    .clusterGrid1_q0(clusterGrid1_q0),
    .clusterGrid1_address1(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address1),
    .clusterGrid1_ce1(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce1),
    .clusterGrid1_we1(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_we1),
    .clusterGrid1_d1(grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_d1),
    .clusterGrid1_q1(clusterGrid1_q1)
);

naive_findClustersHLS2_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start),
    .ap_done(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_done),
    .ap_idle(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_idle),
    .ap_ready(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_ready),
    .grid_address0(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_address0),
    .grid_ce0(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_ce0),
    .grid_q0(grid_q0),
    .clusterGrid1_address0(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address0),
    .clusterGrid1_ce0(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce0),
    .clusterGrid1_q0(clusterGrid1_q0),
    .clusterGrid1_address1(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address1),
    .clusterGrid1_ce1(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce1),
    .clusterGrid1_q1(clusterGrid1_q1),
    .clusterGrid2_address1(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_address1),
    .clusterGrid2_ce1(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_ce1),
    .clusterGrid2_we1(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_we1),
    .clusterGrid2_d1(grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_d1)
);

naive_findClustersHLS2_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start),
    .ap_done(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done),
    .ap_idle(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_idle),
    .ap_ready(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_ready),
    .grid_address0(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_address0),
    .grid_ce0(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_ce0),
    .grid_q0(grid_q0),
    .pointsGrid_address0(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_address0),
    .pointsGrid_ce0(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_ce0),
    .pointsGrid_we0(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_we0),
    .pointsGrid_d0(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_d0),
    .clusterGrid1_address0(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_address0),
    .clusterGrid1_ce0(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_ce0),
    .clusterGrid1_q0(clusterGrid1_q0),
    .clusterGrid2_address0(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_address0),
    .clusterGrid2_ce0(grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_ce0),
    .clusterGrid2_q0(clusterGrid2_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_ready == 1'b1)) begin
            grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg <= 1'b1;
        end else if ((grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_ready == 1'b1)) begin
            grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_ready == 1'b1)) begin
            grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        clusterGrid1_address0 = grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        clusterGrid1_address0 = grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        clusterGrid1_address0 = grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address0;
    end else begin
        clusterGrid1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        clusterGrid1_address1 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        clusterGrid1_address1 = grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        clusterGrid1_address1 = grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_address1;
    end else begin
        clusterGrid1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        clusterGrid1_ce0 = grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        clusterGrid1_ce0 = grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        clusterGrid1_ce0 = grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce0;
    end else begin
        clusterGrid1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        clusterGrid1_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        clusterGrid1_ce1 = grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        clusterGrid1_ce1 = grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_ce1;
    end else begin
        clusterGrid1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        clusterGrid1_d1 = 16'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        clusterGrid1_d1 = grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_d1;
    end else begin
        clusterGrid1_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        clusterGrid1_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        clusterGrid1_we1 = grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_clusterGrid1_we1;
    end else begin
        clusterGrid1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        clusterGrid2_address1 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        clusterGrid2_address1 = grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_address1;
    end else begin
        clusterGrid2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        clusterGrid2_ce0 = grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_clusterGrid2_ce0;
    end else begin
        clusterGrid2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        clusterGrid2_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        clusterGrid2_ce1 = grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_ce1;
    end else begin
        clusterGrid2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        clusterGrid2_d1 = 16'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        clusterGrid2_d1 = grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_d1;
    end else begin
        clusterGrid2_d1 = 'bx;
    end
end

always @ (*) begin
    if (((grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        clusterGrid2_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        clusterGrid2_we1 = grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_clusterGrid2_we1;
    end else begin
        clusterGrid2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grid_address0 = grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grid_address0 = grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grid_address0 = grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_address0;
    end else begin
        grid_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grid_ce0 = grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_grid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grid_ce0 = grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_grid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grid_ce0 = grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_grid_ce0;
    end else begin
        grid_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start = grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_ap_start_reg;

assign grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start = grp_naive_findClustersHLS2_Pipeline_FirstPass_FirstPassInner_fu_85_ap_start_reg;

assign grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start = grp_naive_findClustersHLS2_Pipeline_SecondPass_SecondPassInner_fu_92_ap_start_reg;

assign pointsGrid_address0 = grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_address0;

assign pointsGrid_ce0 = grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_ce0;

assign pointsGrid_d0 = grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_d0;

assign pointsGrid_we0 = grp_naive_findClustersHLS2_Pipeline_CreateResult_CreateResultInner_fu_100_pointsGrid_we0;

endmodule //naive_findClustersHLS2
